### ISSUE TITLE
Invalid UUID

### ISSUE THREAD

**Issue by thefosk** [thibaultcha/lua-resty-jit-uuid#8]
The following UUID seems to be invalid `46c47c5e-d3b8-4c7a-cc5f-8d1fd989dde0`:

```lua
local uuid = require "resty.jit-uuid"

uuid.is_valid("46c47c5e-d3b8-4c7a-cc5f-8d1fd989dde0") -- Is false, but why?
```

Why?

**Comment by thefosk** [comment]
I was also able to replicate this problem with `1c6284fc-0bdd-46c9-c672-2161d1e67ea4`.

**Comment by Tieske** [comment]
my 2cts; has to do with the uuid types. Previously it just generated random stuff (might be related to this; https://github.com/Tieske/uuid/pull/7 ).

The new validator also verifies the uuid type indication stored in the uuid. That's where it fails.

see https://github.com/thibaultcha/lua-resty-jit-uuid/blob/master/lib/resty/jit-uuid.lua#L73

**Comment by Tieske** [comment]
fix: either update all uuids, or relax the uuid validator

**Comment by thibaultcha** [comment]
Those are indeed invalid UUIDs according to RFC 4122 due to their variant field not being correctly set (for RFC 4122 only). Those uuids were probably generated from lua-uuid, which had that issue.

If not desired, one can use a custom UUID validator function (ideally relying on the same tricks this module is for optimized performance).
